### ISSUE TITLE
faulty Unicode fix

### ISSUE THREAD

**Issue by loveencounterflow** [mcollina/levelgraph#106]
It occurred to me that pull request #97, specifically https://github.com/mcollina/levelgraph/commit/cb081cd5cbb54e9294b114a028f857710282ba4f#diff-4d89d5c644f0a717b45ab7306c44bd6cL928, is not correct.

The PR suggests to replace `\xff` ('ÿ') by `\uffff` on the grounds that "the unicode character would be greater than the ascii character '\xff', so the upper bound should be '\uffff'". However, while the complaint is correct, the solution is not—U+FFFF is nowhere close to the greatest legal codepoint of Unicode. As a quick look at http://en.wikipedia.org/wiki/Unicode will show, the last legal codepoint of Unicode is U+10FFFF. 

In figures, this means that while the solution using `\xff` missed out on 1,114,111 – 256 = 1,113,855 possible codepoints, the new solution will still miss out on  1,114,111 – 65,536 = 1,048,575 codepoints, so the relative region of failure has shrunk from 99.977% to 94.118%. 

Still, the new solution is wrong for over 94 out of 100 randomly selected Unicode code points.

I've made a [gist as a demo](https://gist.github.com/loveencounterflow/cb0b76c9d5d0b64137b0); basically, what it shows is that you can actually use `~` as the 'last character' and you'll be fine until the day the first German umlaut `äöü` comes in; all of a sudden, `~` looks broken because Unicode chose to follow ISO8859-1 and place `ä` at a higher position than `~`. `~` works for a lot of Americans who don't accents and manage to live on 7 bits, so you can find a fair number of recommendations to use `~` for your LevelDB field separators and query keys.

The shortcomings of `~` are easily fixed by swapping it out for `\xff`. As the author of http://dailyjs.com/2013/05/03/leveldb-and-node-2/ recommends, we can "go right to the edges of the single-byte character range and use '\x00' (null) or '\xff' (ÿ)", also "''\xff' comes in handy here because we can use it to include every string of characters preceding it". I'm probably preaching the choir here, but this is of course nonsense. As the demo output in the gist shows, it's true, German umlauts are in, yay. But, alas, the Greek alphabet, the Arabic Abjad, Hindi, Ethiopic, Tibetan, Katakana, IPA, Cherokee, Zapf Dingbats, Hebrew and Javanese are still not covered.

So let's raise the bar and opt for `\uffff`. This number reifies the assumption that Unicode operates on 16bit codepoints—which used to be true until 1996 when version 2 got published. JavaScript, it's true, is a little older than that and still does have its issues when comes to the Astral Planes, but then NodeJS, major browsers and LevelDB do manage the situation quite well. Long story short: although it takes some tricky ingredients like CESU-8 and surrogate pairs, codepoints represented in 'good' encodings will sort according to their numerical positions in LevelDB *even when they take up more than 16 bits*. 

This is borne out by the test output in the gist, where i show how even a key like `a𠁩` (consisting of codepoints U+0061 and U+20069): 
* sorts behind other stuff like `aä`, `aΔ`, and `a中`;
* is **not captured** when using `\uffff` as delimiter;
* but **is captured** when using **an octet, not a character `0xff`, decimal 255** as delimiter.

This works because in UTF-8 / CESU-8, `0xff` can never appear as an octet value.

i suggest to review the code portion in question and, for the delimiter, either use:
* an octet / byte value of `0xff`,
* or a suitable representation of U+10FFFF, 
* or a suitable representation of U+110000.

'Suitable representation' means 'a representation that works as intended'; this includes, but is probably not limited to, using a surrogate pair. i include both U+110000 and U+10FFFF because the former is technically not a legal Unicode code point, so some software may justifiably fail when encountered.

Personally i'm injecting `0xff` octets as delimiters in the `lte` parts of my LevelDB queries; this has worked so far, although the resulting buffer as such cannot be interpreted as a valid UTF-8 or CESU-8 encoding any more. Then again, LevelDB as such only cares for bytes, not for characters, so that should be allright.

**Comment by mcollina** [comment]
What a post! Thank so much for the clarification! Would you like to send a PR with your best fix, I definitely trust you on this issue, as you happen to know much more than me on unicode.

**Comment by snowyu** [comment]
thanks very much. now use the <U+10FFFF> instead.

**Comment by loveencounterflow** [comment]
looks good, tested https://github.com/snowyu/levelgraph/commit/9f83451a8261380e161fd7e31a8d3e0042970926 with the code in the gist and works as expected. the only possible character sequence the fix (using `'\udbff\udfff'`, which is fine) doesn't catch are completely exotic and probably not even fully 'legal' Unicode, since U+10FFFF is reserved but not defined, so those can be safely neglected.

**Comment by mcollina** [comment]
@snowyu merge it and ping me, I'll get it published asap.

**Comment by snowyu** [comment]
@mcollina  done.
@loveencounterflow  sorry for my obsolete unicode knowledge.  In my past era, unicode only 2 bytes. I remember I used to think: two bytes is sufficient, unless the ET aliens come. Did not expect to actually have now expanded to a four-byte(21bits) unicode. maybe I am too old to code.

**Comment by mcollina** [comment]
Released as 0.10.2.

**Comment by loveencounterflow** [comment]
@snowyu never mind, encodings are difficult, Unicode is difficult. i do it for a living so i have to know. and most things about Unicode i certainly do *not* know...
