### ISSUE TITLE
Uncaught TypeError: not implemented

### ISSUE THREAD

**Issue by silentrob** [mcollina/levelgraph#108]
Perhaps someone can point me in the right direction as there are lots of moving parts.

I'm trying to create multiple sub level (graph DB's) and persist the subgraph db name in a mongo store.
When I put the graph down and pick it back up again I get the following error.
I'm only saving the graph name (string) in mongo so it should be able to re-use it and the code seems like it should work. 

I suspect it is the master level db is out of step but Im not sure how to verify.

  Uncaught TypeError: not implemented
      at DeferredLevelDOWN._iterator (/Users/furrykitten/projects/sfacts/node_modules/level/node_modules/level-packager/node_modules/levelup/node_modules/deferred-leveldown/deferred-leveldown.js:44:9)

**Comment by mcollina** [comment]
I think your are making some mistakes there, because that 'not implemented' should definitely not happen. Can you post some code to show the issue in its smallest form?

**Comment by silentrob** [comment]
Thanks for the quite reply. I will see if I can repo it with much less code, and post it.

**Comment by silentrob** [comment]
Reducing the problem helped. It turns out my test runner we calling db.close() in the after hook and that was generating the error above. I'm still getting a locked process but I think Im on the right path to sanity.

**Comment by mcollina** [comment]
Perfect! So I think we can close this :rocket:!

**Comment by silentrob** [comment]
Yep, thanks
