### ISSUE TITLE
Event wrapper in levelgraph

### ISSUE THREAD

**Issue by silentrob** [mcollina/levelgraph#110]
Im using sublevel and levelgraph and noticed that sublevel supports events (level-sublevel supports hooks)

It would be nice if levelgraph could wrap or extend that, or perhaps Im doing it wrong.

    var createDB = function(level) {
        var sub = require('sublevel')(level);
        var graphLevel = sub.sublevel(dbname);
        graphLevel.db = level.db;
        graphLevel.approximateSize = level.db.approximateSize.bind(level.db);

        return require('levelgraph')(graphLevel);
    }

    var ua = createDB('userDB');
    ua.on('put',...)

**Comment by mcollina** [comment]
I am not getting what are you trying to achieve here. You should be able to pass a sublevel in place of a Level instance.

See https://github.com/mcollina/levelgraph/blob/master/test/abstract_sublevel_support.js#L13-L14

**Comment by silentrob** [comment]
That does seems a lot easier then what Im trying to. When I first tried setting it up a few months back I was getting an error that seemed to suggest I needed to patch approximateSize.

Ahh it was here - https://github.com/mcollina/levelgraph/issues/87

**Comment by mcollina** [comment]
Can this be closed then?
Il giorno ven 30 gen 2015 alle 09:16 Rob Ellis <notifications@github.com>
ha scritto:

**Comment by silentrob** [comment]
Ill update my code and re-open the issue if I get blocked.
Thanks
