### ISSUE TITLE
Node 0.12.0 support

### ISSUE THREAD

**Issue by silentrob** [mcollina/levelgraph#115]
Im in the process of moving some code to Node 0.12 and noticed https://github.com/mcollina/levelgraph/blob/master/package.json#L36

Have you tested or noticed any issues with 0.12.x?

**Comment by mcollina** [comment]
Just me being lazy and not updating it. Since the release of leveldown 0.10.4 this is going fine.

**Comment by silentrob** [comment]
Perfect, thank you. I didn't see anything wrong when I updated it, I just wanted to make sure.
