### ISSUE TITLE
SPAEQL like database search?

### ISSUE THREAD

**Issue by shuanzi** [mcollina/levelgraph#117]
Hi, All~
Is there any way that can astract the sb.search() method into a SPARQL way or SQL way ?
Would that be more convenient?

Do you guys have any advice or clue? That would be a great help.

Thanks,all~

**Comment by mcollina** [comment]
I would suggest to look into https://www.npmjs.com/package/sparql-parser and write a levelgraph-sparql module :)

**Comment by shuanzi** [comment]
Thanks for your advice! I will look into that.
