### ISSUE TITLE
Anybody seeing 'dummy_versions_.next_ == &dummy_versions_' errors?

### ISSUE THREAD

**Issue by DinisCruz** [mcollina/levelgraph#122]
I just stated seeing this error

![image](https://cloud.githubusercontent.com/assets/656739/7668255/3abbae44-fc25-11e4-9f57-99be3fb62459.png)
```ssh
Assertion failed: (dummy_versions_.next_ == &dummy_versions_), function ~VersionSet, file ../deps/leveldb/leveldb-1.14.0/db/version_set.cc, line 803.
```

which looks like it is related to https://github.com/BVLC/caffe/pull/1814

**Comment by mcollina** [comment]
Not really. You might want to report it in the [leveldown](https://github.com/level/leveldown) package, as it is the place where alle the C++ magic happens.

**Comment by DinisCruz** [comment]
thx, for reference I think I tracked that error to an unit test that was calling done twice (which was triggering an ```aftereach``` db clean up code
