### ISSUE TITLE
n3 and jsonld seem complicated. how to use levelgraph with json objects?

### ISSUE THREAD

**Issue by serapath** [mcollina/levelgraph#124]
Hey, maybe it's supposed to be used next to a normal leveldb to manage `json blobs`.
But how can i store some more content or associate more content with an "object" in the sense of
{ object: ..., predicate: ..., subject: ...} ?

If i have  `a =b=> c` and  `e =b=> c`  and `c =d=>e`, then `c` is a short string name for that node, but maybe i'd like to attach mor stuff to c than just it's name?
Can i serialize a json object into a graph and get it back out?

Are there some cool examples? What could I read? Or could someone give me a short generic example how to go about it? (basically to enrich my seperate json files or objects by defining some graph connections between them - i never used graph databases yet, but would like to play around with them)

**Comment by mcollina** [comment]
jsonld is quite simple, as it will store al properties of your object in the graph. A mixed approach is not supported, you should generate ids, and store the JSON blob in level while using LG for indexing.

Unfortunately I have not example, but it should be easy to roll out. If you do, consider releasing a new module on that, as we would love it!

**Comment by serapath** [comment]
thx, that was my thought too.
I'd use LG for indexing and a normal level for storing blobs :-)
Before actually creating any special module for it, i would use it in my planned project and once i have enough experience i would love to contribute something :-)

thx for taking time to respond :-)
