### ISSUE TITLE
What is the maximum database size in levelgraph?

### ISSUE THREAD

**Issue by alexmgarcia** [mcollina/levelgraph#126]
Hi,
Thank you for your work. It does exactly what I was looking for.
I would like to know if there is a maximum database size in levelgraph (although it is built upon leveldb). I checked the created database in Chrome and it is stored in IndexedDB, so as I am using it for a hybrid mobile app with Cordova, I would like to know that because IndexedDB have a different maximum size in different browsers

**Comment by mcollina** [comment]
There is no limit in node. I tested it with 10 millions triples (60
millions records), and it was working fine.

There are some catch in importing stuff.

Regarding the size in browsers, check their docs and divide it by 6.
Il giorno mar 30 giu 2015 alle 17:12 alexmgarcia <notifications@github.com>
ha scritto:

**Comment by alexmgarcia** [comment]
Thank you!

**Comment by ariugwu** [comment]
Can you explain the "catch in importing stuff"? I'm currently trying to insert 2million triples and the memory  usage spikes really high.

**Comment by mcollina** [comment]
Define high :). How are you doing the import?
