### ISSUE TITLE
Number of matches

### ISSUE THREAD

**Issue by pabloem** [mcollina/levelgraph#128]
Hi Matteo,
I'm working on a feature where it would be useful to return an expected number of matches for a given query, without actually returning the matched triples themselves. This is, among other reasons, because the list may be way too large. Do you think this would be a pertinent feature?
Best
P.

**Comment by mcollina** [comment]
There is: https://github.com/mcollina/levelgraph/blob/master/lib/levelgraph.js#L103-L108

However it will not work in the browser and under some leveldown implementations, but the stock level should be supported. Let me know if it solves your problem.

**Comment by pabloem** [comment]
this is what I need. Thank you very much.
