### ISSUE TITLE
How to return triple properties from a search?

### ISSUE THREAD

**Issue by Wu-Li** [mcollina/levelgraph#129]
Hello again. 
I've been storing my node properties using triple properties which have the node as both the subject and object. Now, I understand that I can't query against these properties (except in the filter), but is it possible to somehow return them from a search/searchStream? 

I can get the properties if i use db.get, but the searches i'm running are more complicated than db.get is capable of. I could pass each of the results from a search to a db.get, but this is incredibly slow. If I log the solutions that are passed through the filter function, I can see that the triple properties are there, but I can't for the life of me figure out how to capture them as part of the output of the search.

I can get the properties by using the Navigator and using the triples function, but (and this may well just be my ineptitude) I can't seem to build any consistent queries with the nav.

Here is the code for my Cursor class, which takes a string and formats it as a levelgraph query:
(please pardon the CoffeeScript)
```
  class Cursor
    run: (@db,@path) =>
      query = []
      lines = @text.split('\n')
      for line in lines
        if line.length != 0
          queryRow = {}
          [subject,predicate,object,properties...] = line.trim().split(' ')
          queryRow.subject = subject
          queryRow.predicate = predicate
          queryRow.object = object
          for prop in properties
            queryRow[prop] = @db.v prop ### <--- What should I be doing here instead?? ###
          query.push queryRow
      stream = @db.searchStream query
      stream.on 'data', (data) ->
        console.log data
```

Thank you in advance for any help. I'm really stumped on this one.
Wu-Li

**Comment by mcollina** [comment]
What data are you storing in the properties? Probably it needs to be a triple too.

**Comment by Wu-Li** [comment]
* Node value
* Node attr - a JSON object containing the CSS classes and HTML attributes of the node

Entering all of these values as independent triples was actually the first approach I tried. However, once I started running queries on that data, it seemed like I was getting very unpredictable results because of the value and JSON nodes. For example, if a node has a value of 42, that doesn't mean it is connected to every other node that also has a value of 42. When trying to query nodes connected to the JSON nodes, it seemed like all objects were treated as a single "Object" node. 

Trying to pass the search results of one query to a second query or a db.get doesn't scale very well. The same goes for running a predicate filter at each step of the query traversal. In any case, trying to solve this issue in the query means the solution, whatever it is, needs to be included in or adapted to every query in the system.

Using triple properties seems like a good choice for several reasons:
 1. I don't need to query these values, just return them with the node they belong to, so no need to index them.
 2. It creates only 1 additional triple per node, no matter how many properties I add down the road. This not only reduces the number of rows significantly, it also means I only need to filter out one type of predicate when querying for "real" connections in the graph.
 3. It allows me to prevent accidental connections like the examples above without the need to write a complex query and filter.
 4. By querying the properties predicate, I can get the nodes themselves without pulling in unnecessary connections.

Se because of all this, I've restructured my data, and my queries are returning much better results, with much cleaner inputs. Which brings me back to the problem in my first post: I can get the correct nodes in my search now, very consistently, but I can't figure out how to return the triple properties along with my search results. In the code I provided I was trying to specify which properties to include, but that isn't actually necessary. If I query the properties predicate at all, I would like all of the properties included. 

Sorry for the huge wall of text, I've been at this for 3 weeks now, and it's the last major hurdle I need to overcome to publish my current project. Thanks again for your help.

**Comment by mcollina** [comment]
@Wu-Li there is no way to have search results (which are not triples) and triples properties (which are stored in triples) in the same result. Let me be clear: __it is not possible, because you get variables values from search, while you want triples__.

LevelGraph have no idea in how to handle triple properties, they are there originally as a bug, which turned out to be a cool feature. I am OK with any PR that improves the above situation, but I have no time to dedicate to finding a new solution to this issue.

**Comment by Wu-Li** [comment]
Thank you for your feedback Matteo, and I understand completely. I thought that perhaps I was missing something, but if it doesn't work that way, I will figure out how to work around it.
