### ISSUE TITLE
How to backup of the base?

### ISSUE THREAD

**Issue by nicholasess** [mcollina/levelgraph#130]

**Comment by yoshuawuyts** [comment]
@nicholasess I'm not sure I understand your question, can you provide some more information?

**Comment by nicholasess** [comment]
@yoshuawuyts levelgraph has some command to backup the datas?

The mysql has command called mysql dump, what is the similar in levelgraph?

**Comment by yoshuawuyts** [comment]
All I found about backing up LevelDB is this - https://twitter.com/tomgco/status/435387541567438848

**Comment by mcollina** [comment]
I would suggest to use [level-hyper](https://github.com/level/level-hyper) and use the internal liveBackup method. See https://github.com/level/leveldown-hyper
