### ISSUE TITLE
Is it possible to search objects connected to subjects with an arbitrary number or predicates in between?

### ISSUE THREAD

**Issue by ludydoo** [mcollina/levelgraph#134]
Hi,

I love this project. I just have a question : 

In neo4j, you can search with cypher like `(:Person)-[*]-(Person)`

Is it possible to do this with levelGraph?

**Comment by mcollina** [comment]
No, this is not possibly at the moment.

**Comment by jmatsushita** [comment]
Doesn't `levelgraph-recursive` goes some distance to enable this feature? https://github.com/mcollina/levelgraph-recursive
