### ISSUE TITLE
this._readStream.read is not a function

### ISSUE THREAD

**Issue by maxired** [mcollina/levelgraph#145]
Hi,

I am using levelgraph or a local ws server,
```javascript
var multilevel = require('multilevel');
var levelgraph = require("levelgraph");
var websocket = require('websocket-stream')

var ws = websocket('ws://127.0.0.1:3009');

var db = multilevel.client();
const dbStream = db.createRpcStream();

dbStream.pipe(ws).pipe(dbStream);

var levelGraph = levelgraph(db); 
```

when doing my first query, I randomly got the error `Uncaught TypeError: this._readStream.read is not a function`. It indeed looks like the socket at this moment has no `read` method, but I am not sure do do we got the error here.
I was thinking that maybe it was because the connection was not properly initialized, but after some test, I don't think so anymore.

here the begin of the stacktrace

```
nextTriple	@ node_modules/levelgraph/lib/sortjoinstream.js:97
SortJoinStream._transform@node_modules/levelgraph/lib/sortjoinstream.js:156
Transform._read@	/node_modules/readable-strea…:184
Transform._write@	/readable-strea…:172
doWrite	@	node_modules/readable-strea…:279
```

**Comment by mcollina** [comment]
multilevel is not officially supported by levelgraph. There are probably some combined bugs.

I would suggest you to look into multileveldown.

**Comment by maxired** [comment]
Ho, interesting, I thought it was du to https://github.com/mcollina/levelgraph/pull/133

**Comment by mcollina** [comment]
oh @maxired maybe. I'm definitely not sure.
Multilevel is supported from a unit tests point of view then :(.

**Comment by maxired** [comment]
@mcollina anyway, I will be happy to switch to multileveldown if it's supported ;) 
But from my test, it seems to give weird results (for example duplicated results). 
Do you have successfull experience with it ?

**Comment by maxired** [comment]
ok, will let you know, cannot reproduce anymore my original issue

**Comment by jmatsushita** [comment]
I've bumped into the same error. Both the multilevel `_readStream.read is not a function` (with joins) and the multileveldown duplicated results. I'm a bit stuck. @maxired What did you end up doing? @mcollina Would it help to submit failing tests with multileveldown (and multilevel too)?

**Comment by maxired** [comment]
@jmatsushita  I am not sure this is the right fix, but https://github.com/jumprocks/levelgraph/commit/b541a25de96561ea83a13a008249652b630ae313 seems to be ok

**Comment by jmatsushita** [comment]
I had tracked down that fix, but it just returned nothing when used with multilevel, Is that meant to be used with multileveldown?  I’ll try again.

--
Jun Matsushita 
Founder, CEO
iilab - information innovation lab -  iilab.org  - @iilab

cell +49 157 530 86174
xmpp jun@jabber.ccc.de  
pgp D38A 5502 7387 3BF4 B330  7DA2 2A07 F70C A036 E792

**Comment by mcollina** [comment]
I'm ok in a PR that add a test and maybe a fix for this issue. Thanks!

**Comment by jmatsushita** [comment]
@mcollina I'll get started with the test!

@maxired I'm afraid this fix just fails silently on joins with multilevel.
