### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by ddibiase** [mcollina/levelgraph#151]
Hello! Is this project still active? What's the current status...? :-)

Thanks!

**Comment by mcollina** [comment]
This project is maintained. I review all PRs, and assemble releases. I am not developing new features or writing new things myself.
Let me know if you want to help maintaining this!

**Comment by ddibiase** [comment]
Grazie mille @mcollina. Sono felice che il progetto e ancora attivo. Mantenere il buon lavoro! =)
