### ISSUE TITLE
Question: Searching depth and recursion

### ISSUE THREAD

**Issue by ddibiase** [mcollina/levelgraph#153]
Hi there,

I'm still very new to graphs so bear with me. I'd like to run a search against the graph I built but I'm wondering how to perform a recursive search with one query OR select the depth of the query. Let's say my graph structure in 5 levels deep and I want to query the full 5 without knowing the depth.

The other question I have is mostly out of curiosity as I haven't studied the implementation code, for filtering in levelgraph does the db pass all the results to the library and then filter in memory or does the database accept the filtering function and perform the logic internally? I only ask because if it's more load on the client to perform filters I may opt for a different graph structure.

Grazie mille,

David

**Comment by mcollina** [comment]
You can try with https://github.com/mcollina/levelgraph-recursive.

I kept it as a separate module because I did not have enough time to integrate.
I'm not 100% sure it will be performant, consider it as an experiment.
