### ISSUE TITLE
How to expose Levelgraph API over Multilevel

### ISSUE THREAD

**Issue by Industrial** [mcollina/levelgraph#159]
Hi!

https://github.com/juliangruber/multilevel/issues/90#issuecomment-267648801

**Comment by mcollina** [comment]
Thanks for sending me a link :). I do not have time right now to assess this issue, but I'm very happy to review/merge one of your pull requests.
As you can guess, I need help in maintaining this module.

There are also several open PRs and issues, so you might found something useful there, too.

Closing, as a "link" is not a real issue. Feel free to reopen or to send a PR.
