### ISSUE TITLE
exact matching not working

### ISSUE THREAD

**Issue by cduret** [mcollina/levelgraph#85]
I encounter a bug(?) when doing a get request with an id and expecting one result but having more results (it is not doing an exact match).

var db = require('levelgraph')('test')
db.put({ subject: 'asset_1', predicate: 'is', object: 'Asset' }, console.log);
db.put({ subject: 'asset_11', predicate: 'is', object: 'Asset' }, console.log);
db.put({ subject: 'asset_12', predicate: 'is', object: 'Asset' }, console.log);

db.get({subject: 'asset_1', predicate: 'is', object: 'Asset'}, console.log);

actually returns : 

null [ { subject: 'asset_1', predicate: 'is', object: 'Asset' },
  { subject: 'asset_11', predicate: 'is', object: 'Asset' },
  { subject: 'asset_12', predicate: 'is', object: 'Asset' } ]

Should returns : 
null [ { subject: 'asset_1', predicate: 'is', object: 'Asset' } ]

**Comment by doowb** [comment]
I'm running into this same issue. Has anyone done a fix yet?

**Comment by cduret** [comment]
don't remember but seems to have something to do in genKeyWithEnding function in sortjoinstream.js

**Comment by mcollina** [comment]
No, unfortunately I am very low on time to dedicate to this at the moment. Would anybody want to have a look, and in general help me maintaining this project? I am more than happy to give the commit bit :).

**Comment by doowb** [comment]
I'll dig into this more today. Thanks @cduret for pointing to `genKeyWithEnding`.

One question: Is the intention of `.search` to do exact matches too but give the ability to use `db.v('foo')`, or are the matches supposed to be partial?

I'm also happy to help maintain this project (username is the same for npm if you want to give publish rights too).

**Comment by mcollina** [comment]
Thanks so much @doowb!

Only exact matches.

I gave you the commit bit, welcome to LevelGraph! I will be still doing formal releases for the time being, so no worries about npm.
Feel free to add your details in the README.md in your coming PR about this issue.
