### ISSUE TITLE
Close and delete database (can it be done without having to also adding level and leveldown as npm dependencies)

### ISSUE THREAD

**Issue by DinisCruz** [mcollina/levelgraph#91]
In order to write the tests you can see at https://github.com/DinisCruz/LevelGraph_Test/tree/master/tests I had to be quite aggressive in closing the db, or multiple mocha executions (using watch) would fail (due to the db files being locked by the OS)

To make it work, I had to npm install  ***level*** and ***leveldown*** and use their ```.close``` method (the LevelGraph DB ```.close``` method didn't seem to release the files correctly

form https://github.com/DinisCruz/LevelGraph_Test/blob/master/src/ArticlesGraph.coffee

here is the code that opens, closes and deletes the DB
![image](https://cloud.githubusercontent.com/assets/656739/4497697/8dd5d8d6-4a71-11e4-8a4f-bc798011ab57.png)

here is the mocha test
![image](https://cloud.githubusercontent.com/assets/656739/4497670/5176df84-4a71-11e4-80a1-7314008a1784.png)

So my question is if there a way to just install LevelGraph (specially since I want to avoid having to npm compile levelup and leveldown multiple times).

Btw, is that the best way to delete the DB files? I saw a reference to a ```.destroy``` method (but couldn't get it to work)

Thanks

**Comment by tilgovi** [comment]
Found this while searching for my issue. It seems it can be closed.
I was searching for an answer to why level-down was a dependency, and wondering if maybe it can be only a devDependency for those using alternative leveldown implementations. Should I open a separate issue for this?

**Comment by mcollina** [comment]
@tilgovi yes please. The whole relationship with leveldown needs to be refactored anyway, so if you want to send a PR for it, I will be super-happy.

Thanks for assessing this, I'm closing
